############################
## CHANGE THESE
############################

#baseURL: 'https://chrede88.github.io/qubt'
#title: 'Qubt Theme'
baseURL: "https://suawiu.github.io/"
title: "suawiu"
theme: "qubt"

############################
## MISC
############################

enableEmoji: true
disableKinds: []
languageCode: 'en-us'
enableRobotsTXT: true

taxonomies:
  category: "categories"
  tag: "tags"

markup:
  goldmark:
    extensions:
      passthrough:
        enable: true
        delimiters:
          block:
            - - \[
              - \]
            - - $$
              - $$
          inline:
            - - \(
              - \)
            - - $
              - $
  _merge: deep
