############################
## Author
############################
author:
  name: 'Seungmin Cha'
  image: images/photo.jpeg
  greeting: |
    This blog serves as a personal research notebook dedicated to documenting my journey and expertise in physics and other interesting fields.
    I aim to systematically archive my academic growth and share meaningful insights with peers in both academia and industry.


  #icon: ':wave:'

############################
## Links
############################

links:
  - github: https://github.com/suawiu
  # - gitlab:
  # - facebook: ""
  # - x-twitter:
  # - mastodon:
  - linkedin: https://www.linkedin.com/in/seungmin-cha-9a22262b1/
  # - instagram: ""
  # - reddit:
  # - telegram:
  # - whatsapp:
  # - signal:
  # - codepen:
  # - dev:
  - email: mailto:chacha1221@naver.com
  # - website: https://github.com/chrede88/qubt
  # - link:
  # - discord:
  # - orcid:
  # - slack:
  # - stack-overflow:
  # - twitch:
  # - patreon:
  # - soundcloud:
  # - dribbble:
  # - stack-exchange:
  # - tiktok:
  - youtube: https://youtube.com/@suawiu?si=i1Ep8zbLyb4vcydc
  # - keybase:
  # - flickr:
  # - tumblr:
  # - kickstarter:
  # - snapchat:
  # - bluesky:
  # - bitbucket:
  # - bandcamp:
  # - etsy:
  # - spotify:
  # - pinterest:
  - strava: https://www.strava.com/athletes/suawiu 
  # - untappd:
  # - skype:
  # - medium:
  # - foursquare:
  # - apple:
  # - amazon:
  # - google:
  # - paypal:
  # - pgp-key:
  # - windows:
  # - codeberg:
  # - pixelfed:
  # - substack:
  # - newsletter:

###############################
## OpenGraph & Twitter Cards
###############################

title: 'Qubt Theme'
description: 'Archive of Suawiu'
images:
  - favicon2.png

###############################
## Latex math
###############################

# To configure Latex rendering on all pages, change to: true
#
# To only add Latex rendering on pages that need it, set in the frontmatter
# of each page that needs it:
#   params:
#     math: true
# This option will allow better performance, as it'll only load
# the extra JS when needed.
math: false
